site_name: Implementación e Implantación de Sistemas Software
site_description: Apuntes de Implementación e Implantación de Sistemas Software – Grado en Ingeniería Informática
site_author: Juan Manuel Dodero
site_dir: 
nav:
    - Inicio: index.md
    - Asignatura:
        - Presentación: iiss-pres.md
        - Bibliografía: bibliografia.md
        - About: about.md
    - Temario: iiss-temas.md
    - I. Objetos:
        - Principios: iiss-oop-1.md
        - Delegación: iiss-oop-2.md
        - Inyección: iiss-oop-3.md
        - Duplicación: iiss-oop-4.md
        - Calidad: iiss-err.md
    - II. Aspectos: iiss-aop.md
    - III. Contratos: iiss-dbc.md
    - IV. Funciones: iiss-fp.md
    - V. Eventos: iiss-evp.md
theme:
    name: 'material'
    logo:
        icon: "\uE80C"
markdown_extensions:
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:pymdownx.emoji.twemoji
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde    
    - admonition
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true
        baselevel: 0
    - sane_lists
extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'    
extra:
    search:
        language: 'en, es'
repo_url: 'https://github.com/dodero/gii-dss-iiss/'
extra:
    social:
      - type: 'github'
        link: 'https://github.com/dodero'
      - type: 'twitter'
        link: 'https://twitter.com/jmdodero'
